---
title: "Untitled"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


https://public.tableau.com/app/profile/ca.open.data/viz/COVID-19CasesDashboardv2_0/CaseStatistics





```{r}
library(dplyr)
library(ggplot2)
library(readr)

covid_re_url <- "https://data.chhs.ca.gov/dataset/f88f9d7f-635d-4334-9dac-4ce773afe4e5/resource/b500dae2-9e58-428e-b125-82c7e9b07abb/download/covid19demographicratecumulative.csv"

covid_re     <- read_csv(covid_re_url) %>%  
                   filter(county == "California", demographic_set == "race_ethnicity")



ggplot(data=covid_re, aes(x=demographic_set_category, y=metric_value_per_100k)      ) + geom_bar(stat = "identity") +
   facet_grid(rows=vars(metric), scales = "free")



covid_re_2 <- covid_re %>% select(metric, demographic_set_category,  
                                  N = metric_value,
                                  Rate = metric_value_per_100k)  %>%
               pivot_longer(cols=N:Rate)

ggplot(data=covid_re_2, aes(x=demographic_set_category, y=value)      ) + geom_bar(stat = "identity") +
   facet_grid(rows=vars(metric), cols=vars(name), scales = "free")




```


```{r}




library(dplyr)
library(readr)
library(summarytools)
library(ggplot2)
library(tidyr)


covid_re_url <- "https://data.chhs.ca.gov/dataset/f88f9d7f-635d-4334-9dac-4ce773afe4e5/resource/b500dae2-9e58-428e-b125-82c7e9b07abb/download/covid19demographicratecumulative.csv"
covid_re     <- read_csv(covid_re_url) %>%  filter(county == "California", demographic_set == "race_ethnicity")


ggplot(data = covid_re, aes(x=demographic_set_category,y=metric_value_per_100k, fill=demographic_set_category)) + geom_bar(stat="identity") + facet_grid(rows=vars(metric), scales="free")



covidODP <- "https://data.chhs.ca.gov/dataset/f333528b-4d38-4814-bebb-12db1f10f535/resource/046cdd2b-31e5-4d34-9ed3-b48cdbc4be7a/download/covid19cases_test.csv"

covid_data <- read_csv(covidODP)






covid_data_ca <- covid_data %>% 
                  filter(area == "California") %>%
                  select(population, date, cases, deaths)
                    



ggplot(data = covid_data_ca, aes(x=date,y=cases)) + geom_line()
ggplot(data = covid_data_ca, aes(x=date,y=cases)) + geom_bar(stat="identity")



covid_data_ca <- covid_data_ca %>% pivot_longer(cols=cases:deaths)

ggplot(data = covid_data_ca, aes(x=date,y=value, col=name)) + geom_line()


freq(covid_data$area)
```



```{r}

server <- function(input, output) {

        output$cmap <- renderggiraph({
            
            g <- ggplot(map.data) +
                geom_sf() +
                geom_sf_interactive(aes(tooltip = county,
                                        data_id = county),
                                    size = 0.5) +
                theme(axis.line=element_blank(),
                      axis.text.x=element_blank(),
                      axis.text.y=element_blank(),
                      axis.ticks=element_blank(),
                      axis.title.x=element_blank(),
                      axis.title.y=element_blank(),
                      legend.position="none",
                      panel.background=element_blank(),
                      panel.border=element_blank(),
                      panel.grid.major=element_line(colour = "transparent"),
                      panel.grid.minor=element_blank(),
                      plot.background=element_blank())
            
            ggiraph(code = print(g),
                    height_svg = 8,
                    selection_type = "single",
                    hover_css = "cursor:pointer;fill:blue;stroke:blue;")
            
        })
        
    
}



```




